### ISSUE TITLE
Comile errors under linux: ambiguous reference to 'tuple'

### ISSUE THREAD

**Issue by lupylucke** [auriocus/PhotoResize#1]
Compilation under linux fails with error messages about ambiguous references to 'tuple'. Full output of 'make': [errmsg.txt](https://github.com/auriocus/PhotoResize/files/764637/errmsg.txt)

A little more info:
- Arch linux
- gcc (GCC) 6.3.1 20170109
- tcl/tk 8.6.6

Renaming the custom 'tuple' struct fixes the issue:
[tulpe-fix.diff.txt](https://github.com/auriocus/PhotoResize/files/764653/tulpe-fix.diff.txt)

**Comment by auriocus** [comment]
Fixed by removing using namespace std;
